/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author SENA
 */
public class Herencia extends javax.swing.JFrame {

    /**
     * Creates new form Herencia
     */
    public Herencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAtras = new javax.swing.JButton();
        jButtonProfesor = new javax.swing.JButton();
        jButtonEstudiante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("CARNET");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(188, 21, 294, 51);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Escoga el usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(236, 90, 115, 20);

        jButtonAtras.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(102, 102, 255));
        jButtonAtras.setText("ATRAS");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras);
        jButtonAtras.setBounds(210, 320, 151, 35);

        jButtonProfesor.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButtonProfesor.setForeground(new java.awt.Color(153, 153, 255));
        jButtonProfesor.setText("PROFESOR");
        jButtonProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProfesorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonProfesor);
        jButtonProfesor.setBounds(321, 145, 161, 127);

        jButtonEstudiante.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButtonEstudiante.setForeground(new java.awt.Color(153, 153, 255));
        jButtonEstudiante.setText("ESTUDIANTE");
        jButtonEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEstudiante);
        jButtonEstudiante.setBounds(77, 149, 161, 127);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        //Instanciamos el frame de incio
            Menu menu = new Menu ();
            menu.setVisible(true);
            //Dispose mata el proceso anterior 
            dispose();
            
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstudianteActionPerformed
      AprendizI aprendizi = new AprendizI ();
            aprendizi.setVisible(true);
            //Dispose mata el proceso anterior 
            dispose();
    }//GEN-LAST:event_jButtonEstudianteActionPerformed

    private void jButtonProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProfesorActionPerformed
       InstructorI instructori = new InstructorI ();
            instructori.setVisible(true);
            //Dispose mata el proceso anterior 
            dispose();
    }//GEN-LAST:event_jButtonProfesorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Herencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Herencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Herencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Herencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Herencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonEstudiante;
    private javax.swing.JButton jButtonProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
