/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author SENA
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents(); //Inicializa los componentes del frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelClave = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldClave = new javax.swing.JPasswordField();
        jButtonInicar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Incio de Sesion");
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(153, 153, 255));
        jLabelTitulo.setText("Inicio de Sesión");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(130, 40, 309, 50);

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(153, 153, 255));
        jLabelUsuario.setText("Usuario:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(110, 110, 142, 127);

        jLabelClave.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabelClave.setForeground(new java.awt.Color(153, 153, 255));
        jLabelClave.setText("Contraseña:");
        getContentPane().add(jLabelClave);
        jLabelClave.setBounds(80, 220, 170, 50);

        jTextFieldUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(230, 150, 174, 38);

        jPasswordFieldClave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(jPasswordFieldClave);
        jPasswordFieldClave.setBounds(230, 230, 171, 39);

        jButtonInicar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonInicar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButtonInicar.setForeground(new java.awt.Color(153, 153, 255));
        jButtonInicar.setText("Iniciar");
        jButtonInicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInicar);
        jButtonInicar.setBounds(230, 300, 130, 50);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 410, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicarActionPerformed
      
        //Para recojer datos : (nombre del objeto . get (obtener) tipo text
        //Para comparar con equals (si el usuario ingreso lo mismo a equals (Admin) y la cntraseña es igual (equals) )
        //Aparece subrayado por que esta cifrado por que es una contraseña 
        if (jTextFieldUsuario.getText().equals("Admin") && jPasswordFieldClave.getText().equals("1011201964")) {
            
            JOptionPane.showMessageDialog(null, "Bienvenido");
            
            //Instanciamos el frame de menu
            Menu menu = new Menu ();
            menu.setVisible(true);
            //Dispose mata el proceso anterior 
            dispose();
            
        }else{
            
            JOptionPane.showMessageDialog(null, "Revisar datos de inicio de sesion");

        }
        
       
    }//GEN-LAST:event_jButtonInicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInicar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClave;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordFieldClave;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
