/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author SENA
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMenu = new javax.swing.JLabel();
        jButtonCarnet = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jButtonOperacion = new javax.swing.JButton();
        jLabelOperacion = new javax.swing.JLabel();
        jLabelCarnet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jLabelMenu.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabelMenu.setForeground(new java.awt.Color(153, 153, 255));
        jLabelMenu.setText("Menú");
        getContentPane().add(jLabelMenu);
        jLabelMenu.setBounds(250, 20, 110, 60);

        jButtonCarnet.setBackground(new java.awt.Color(204, 204, 255));
        jButtonCarnet.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButtonCarnet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/9.png"))); // NOI18N
        jButtonCarnet.setText("CARNET");
        jButtonCarnet.setMaximumSize(new java.awt.Dimension(300, 170));
        jButtonCarnet.setMinimumSize(new java.awt.Dimension(300, 170));
        jButtonCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarnetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCarnet);
        jButtonCarnet.setBounds(80, 160, 180, 120);

        jButtonCerrar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonCerrar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButtonCerrar.setText("CERRAR SESION");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrar);
        jButtonCerrar.setBounds(180, 80, 240, 40);

        jButtonOperacion.setBackground(new java.awt.Color(204, 204, 255));
        jButtonOperacion.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButtonOperacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mate.jpg"))); // NOI18N
        jButtonOperacion.setText("OPERACIÓN");
        jButtonOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOperacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOperacion);
        jButtonOperacion.setBounds(280, 160, 220, 120);

        jLabelOperacion.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabelOperacion.setForeground(new java.awt.Color(153, 153, 255));
        jLabelOperacion.setText("OPERACION");
        getContentPane().add(jLabelOperacion);
        jLabelOperacion.setBounds(330, 280, 150, 70);

        jLabelCarnet.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabelCarnet.setForeground(new java.awt.Color(153, 153, 255));
        jLabelCarnet.setText("CARNET");
        getContentPane().add(jLabelCarnet);
        jLabelCarnet.setBounds(100, 280, 150, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        
         JOptionPane.showMessageDialog(null, "Su sesion se cerro");
            
            //Instanciamos el frame de incio
            Inicio inicio = new Inicio();
            inicio.setVisible(true);
            //Dispose mata el proceso anterior 
            dispose();
            
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarnetActionPerformed
        
       
            
            //Instanciamos el frame de incio
            Herencia herencia = new Herencia();
            herencia.setVisible(true);
            //Dispose mata el proceso anterior 
            dispose();
            
    }//GEN-LAST:event_jButtonCarnetActionPerformed

    private void jButtonOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOperacionActionPerformed
          //Instanciamos el frame de incio
            Suma suma = new Suma();
            suma.setVisible(true);
            //Dispose mata el proceso anterior 
            dispose();
    }//GEN-LAST:event_jButtonOperacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCarnet;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonOperacion;
    private javax.swing.JLabel jLabelCarnet;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelOperacion;
    // End of variables declaration//GEN-END:variables
}
